export type ToolMeta = {
  slug: string;
  name: string;
  type: string;
  title: string;
  description: string;
  features: string[];
  faqs: { q: string; a: string }[];
};

const SITE = "https://seoacademys.com";

function buildFaqs(name: string, signals: string, frequency = "monthly", advantage = "real-time live-URL checks"): { q: string; a: string }[] {
  return [
    { q: `What is ${name}?`, a: `${name} is a free SEO tool from SEOAcademys that analyzes ${signals} in real time from any live URL. It runs in your browser with no signup and is used by 2.4M+ marketers.` },
    { q: `Is ${name} free?`, a: `Yes, ${name} is 100% free, with no signup or credit card required. It fetches live data directly from the URL you submit and returns results in under 8 seconds.` },
    { q: `How accurate is ${name}?`, a: `${name} fetches data in real time from the live URL — never cached. It evaluates ${signals} using the same methodology as enterprise SEO suites and has been used by 2.4M+ marketers across 80+ countries.` },
    { q: `How does ${name} compare to paid tools?`, a: `${name} provides the same core checks as paid tools like Semrush and Ahrefs, but completely free. Its advantage is ${advantage} and full transparency on every signal evaluated.` },
    { q: `How often should I use ${name}?`, a: `SEO experts recommend running ${name} ${frequency}, and after every major release or content update. Changes to the signals it tracks can affect rankings within 7–30 days.` },
  ];
}

export const TOOL_META: Record<string, ToolMeta> = {
  "ai-citation-audit": { slug: "ai-citation-audit", name: "AI Citation Audit", type: "AI Search Optimization Tool", title: "AI Citation Audit — Free ChatGPT, Gemini & Perplexity Visibility Checker | SEOAcademys", description: "Check if ChatGPT, Gemini, Perplexity & Google AI Overviews cite your site. 47 GEO signals scored live. Free, no signup. Used by 2.4M+ SEOs.", features: ["47 GEO signals scored in real time", "ChatGPT, Gemini, Perplexity & Google AIO coverage", "Citation probability per URL", "Fix-list with priority weighting", "Schema, llms.txt & E-E-A-T scoring", "Sentence-level extractability check", "Exportable JSON & CSV reports"], faqs: buildFaqs("AI Citation Audit", "47 generative-engine ranking signals", "monthly", "AI-engine specific scoring (ChatGPT, Gemini, Perplexity, Google AIO)") },
  "geo-tracker": { slug: "geo-tracker", name: "GEO Market Intelligence", type: "AI Market Tracker", title: "GEO Market Intelligence — Free AI Citation Tracker by Industry | SEOAcademys", description: "Live market data on what AI engines cite most across Tech, Finance, Health & SaaS. Free GEO tracker used by 2.4M+ marketers.", features: ["20+ live citation patterns", "Industry segmentation (Tech, Finance, Health, SaaS)", "Engine-by-engine breakdown", "Source-type distribution", "Weekly trend deltas", "Exportable charts", "Real-time refresh"], faqs: buildFaqs("GEO Market Intelligence", "20+ AI citation patterns across industries", "weekly", "industry-segmented intelligence updated in real time") },
  "content-checker": { slug: "content-checker", name: "Content Readiness Checker", type: "AI Content Score", title: "Content Readiness Checker — Free AI Extraction Quality Scorer | SEOAcademys", description: "Score AI extractability sentence-by-sentence. See exactly which lines ChatGPT can cite. Free, no signup. 2.4M+ marketers use it.", features: ["Sentence-level extractability highlighting", "Claim density scoring", "Entity & fact coverage", "Citation likelihood %", "Readability + LLM friendliness", "Inline rewrite suggestions", "Copy-ready cleaned text"], faqs: buildFaqs("Content Readiness Checker", "sentence-level AI extractability across 12 quality signals", "before every publish", "sentence-by-sentence highlights of what LLMs can and can't cite") },
  "schema-generator": { slug: "schema-generator", name: "Schema & llms.txt Generator", type: "Structured Data Generator", title: "Schema & llms.txt Generator — Free JSON-LD + LLM Manifest | SEOAcademys", description: "Generate production-ready JSON-LD schema and llms.txt files instantly. FAQ, Product, Article, Org, llms.txt. Free, no signup.", features: ["FAQ, Product, Article, Org, How-To schema", "llms.txt manifest builder", "Live JSON-LD preview", "Google Rich Results compatible", "Copy & download as .json / .txt", "Auto-validates required properties", "Multi-block export"], faqs: buildFaqs("Schema & llms.txt Generator", "production-ready JSON-LD and LLM manifest files", "for every new template or content type", "outputs both Schema.org JSON-LD and the new llms.txt standard side-by-side") },
  "seo-audit": { slug: "seo-audit", name: "Full SEO Audit", type: "On-Page SEO Audit", title: "Free SEO Audit Tool — 47-Signal Live On-Page Audit | SEOAcademys", description: "Live SEO audit of any URL. 47 on-page signals: title, meta, headings, Core Web Vitals, schema, mobile. Free, no signup.", features: ["47 on-page SEO signals", "Title, meta, heading & canonical checks", "Schema.org validation", "Mobile-friendliness signals", "Core Web Vitals heuristics", "Prioritized fix list", "0–100 score with breakdown"], faqs: buildFaqs("the SEO Audit Tool", "47 on-page SEO signals including title, meta, headings, schema and CWV", "monthly and after every release", "live HTML fetch with prioritized fix list") },
  "meta-tag-checker": { slug: "meta-tag-checker", name: "Meta Tag Checker", type: "Meta Tag Analyzer", title: "Meta Tag Checker — Live Title, Description & OG Inspector | SEOAcademys", description: "Inspect every meta tag of any live URL — title length, description, Open Graph, Twitter cards. Free, no signup.", features: ["Title & description pixel-width check", "Open Graph (og:*) inspection", "Twitter Card validation", "Robots & canonical detection", "Hreflang summary", "Copy-as-HTML export"], faqs: buildFaqs("the Meta Tag Checker", "every meta, OG and Twitter Card tag on a live URL", "monthly", "pixel-accurate title/description truncation preview") },
  "heading-checker": { slug: "heading-checker", name: "Heading Structure Checker", type: "Heading Outline Analyzer", title: "Heading Structure Checker — Free H1-H6 Outline Tool | SEOAcademys", description: "Visualize H1–H6 outline of any URL. Find missing H1s, skipped levels & duplicate headings. Free, no signup.", features: ["Full H1–H6 tree", "Hierarchy gap detection", "Duplicate H1 warnings", "Keyword density per heading", "Outline export"], faqs: buildFaqs("the Heading Structure Checker", "the complete H1–H6 outline of any URL", "monthly", "tree visualization with hierarchy gap flags") },
  "og-checker": { slug: "og-checker", name: "Open Graph Checker", type: "OG Tag Inspector", title: "Open Graph Checker — Live Facebook & LinkedIn Preview | SEOAcademys", description: "Preview exactly how Facebook & LinkedIn render your share card. Validates all og:* tags. Free, no signup.", features: ["Live FB/LinkedIn preview", "og:* tag completeness", "Image dimension check", "Fallback detection"], faqs: buildFaqs("the Open Graph Checker", "every og:* tag plus the rendered FB/LinkedIn share preview", "before every publish", "pixel-accurate share-card preview") },
  "twitter-card-checker": { slug: "twitter-card-checker", name: "Twitter Card Checker", type: "Twitter / X Card Inspector", title: "Twitter / X Card Checker — Live Preview & Validator | SEOAcademys", description: "See exactly how X (Twitter) renders your share card. Validates twitter:* tags live. Free, no signup.", features: ["Live X share preview", "twitter:* tag validation", "Image aspect-ratio check", "Card type detection"], faqs: buildFaqs("the Twitter Card Checker", "every twitter:* tag plus the rendered X preview", "before every campaign", "live X share preview with image checks") },
  "canonical-checker": { slug: "canonical-checker", name: "Canonical URL Checker", type: "Canonical Validator", title: "Canonical URL Checker — Free Self-Canonical Validator | SEOAcademys", description: "Verify rel=canonical, detect cross-domain conflicts & self-canonical issues. Free, no signup.", features: ["Canonical extraction", "Self-canonical validation", "Cross-domain detection", "Conflict flagging"], faqs: buildFaqs("the Canonical URL Checker", "the rel=canonical link and self-canonical validation", "after every URL change", "cross-domain conflict detection") },
  "robots-checker": { slug: "robots-checker", name: "Robots.txt Checker", type: "Robots.txt Validator", title: "Robots.txt Checker — Validates AI Crawler Rules (GPTBot, ClaudeBot) | SEOAcademys", description: "Validate robots.txt syntax & check AI crawler directives (GPTBot, PerplexityBot, ClaudeBot). Free, no signup.", features: ["Robots.txt syntax parser", "AI-crawler directive audit", "Per-bot allow/disallow matrix", "Sitemap discovery"], faqs: buildFaqs("the Robots.txt Checker", "every User-agent rule including GPTBot, PerplexityBot and ClaudeBot", "monthly", "AI-crawler-specific directive audit") },
  "sitemap-checker": { slug: "sitemap-checker", name: "Sitemap Checker", type: "XML Sitemap Analyzer", title: "Sitemap Checker — Free XML Sitemap & Sitemap-Index Analyzer | SEOAcademys", description: "Parse sitemap.xml and sitemap-index files. Validates URL coverage, lastmod & priority. Free, no signup.", features: ["URL count & coverage", "Sitemap-index expansion", "lastmod / priority audit", "Broken URL flag"], faqs: buildFaqs("the Sitemap Checker", "every URL, lastmod and priority value in sitemap.xml", "monthly", "sitemap-index expansion and per-URL diagnostics") },
  "mobile-checker": { slug: "mobile-checker", name: "Mobile-Friendly Checker", type: "Mobile UX Tester", title: "Mobile-Friendly Checker — Free Mobile SEO & CWV Test | SEOAcademys", description: "Test mobile usability, viewport, tap targets & Core Web Vitals signals. Free, no signup.", features: ["Viewport detection", "Tap-target size audit", "Font-size accessibility", "CWV heuristics"], faqs: buildFaqs("the Mobile-Friendly Checker", "viewport, tap-target, font-size and Core Web Vital heuristics", "monthly", "combined mobile UX + CWV signal scoring") },
  "ssl-checker": { slug: "ssl-checker", name: "SSL / HTTPS Checker", type: "SSL Certificate Tester", title: "SSL Checker — Free HTTPS, HSTS & Mixed-Content Audit | SEOAcademys", description: "Verify HTTPS, HSTS header & mixed-content risk for any URL. Free, no signup.", features: ["HTTPS enforcement check", "HSTS header detection", "Mixed-content scan", "Final-URL trace"], faqs: buildFaqs("the SSL Checker", "HTTPS enforcement, HSTS, and mixed-content signals", "quarterly", "mixed-content scanning of the live HTML") },
  "tech-detector": { slug: "tech-detector", name: "Website Technology Detector", type: "Tech Stack Detector", title: "Website Technology Detector — Free CMS, CDN & Framework Finder | SEOAcademys", description: "Detect CMS, framework, CDN, analytics & more from any live URL. Free, no signup.", features: ["CMS detection (WordPress, Shopify, …)", "Framework detection (Next, Vue, React, …)", "CDN & analytics fingerprinting", "Header-based signals"], faqs: buildFaqs("the Tech Detector", "CMS, framework, CDN and analytics fingerprints", "as needed", "header + HTML signature fingerprinting") },
  "redirect-checker": { slug: "redirect-checker", name: "Redirect Chain Checker", type: "Redirect Tracer", title: "Redirect Checker — Free 301/302 Chain Tracer (Up to 8 Hops) | SEOAcademys", description: "Follow the redirect chain step-by-step (up to 8 hops). Free, no signup.", features: ["Up to 8 redirect hops", "Status code per hop", "Final URL detection", "Loop & chain flag"], faqs: buildFaqs("the Redirect Checker", "the full redirect chain up to 8 hops with status per hop", "after every URL migration", "loop detection with status code per hop") },
  "http-headers": { slug: "http-headers", name: "HTTP Headers Checker", type: "Response Header Analyzer", title: "HTTP Headers Checker — Live Response Header Inspector | SEOAcademys", description: "Inspect every HTTP response header of any live URL. Cache, security, compression. Free, no signup.", features: ["All response headers", "Cache-Control audit", "Security headers (CSP, HSTS, X-Frame-Options)", "Compression detection"], faqs: buildFaqs("the HTTP Headers Checker", "every HTTP response header including cache, compression and security headers", "quarterly", "categorized security/cache/compression review") },
  "page-size": { slug: "page-size", name: "Page Size Analyzer", type: "Page Weight Tool", title: "Page Size Analyzer — Free Page Weight & Asset Breakdown | SEOAcademys", description: "Analyze page weight, asset breakdown & Core Web Vitals impact. Free, no signup.", features: ["Total page weight", "HTML/CSS/JS/Image split", "Request count", "Compression savings estimate"], faqs: buildFaqs("the Page Size Analyzer", "total page weight, asset breakdown and request count", "monthly", "per-asset breakdown with compression savings") },
  "keyword-density": { slug: "keyword-density", name: "Keyword Density Analyzer", type: "Keyword Density Tool", title: "Keyword Density Analyzer — Free 1/2/3-Word Gram Counter | SEOAcademys", description: "Analyze keyword & LSI distribution for any URL or text. 1, 2 & 3-word grams. Free, no signup.", features: ["1, 2 & 3-word grams", "Top-N frequency table", "Stop-word filtering", "Density % per term"], faqs: buildFaqs("the Keyword Density Analyzer", "1, 2 and 3-word phrase density with stop-word filtering", "for every long-form piece", "n-gram density across the full document") },
  "readability": { slug: "readability", name: "Readability Checker", type: "Readability Scorer", title: "Readability Checker — Free Flesch-Kincaid Grade & Score | SEOAcademys", description: "Flesch Reading Ease + grade-level analysis of any text. Free, no signup.", features: ["Flesch Reading Ease", "Words / sentences / paragraphs", "Avg words per sentence", "Grade level interpretation"], faqs: buildFaqs("the Readability Checker", "Flesch Reading Ease and grade-level signals", "before every publish", "live Flesch + grade-level interpretation") },
  "word-counter": { slug: "word-counter", name: "Word & Character Counter", type: "Word Counter", title: "Word & Character Counter — Free Live Counter | SEOAcademys", description: "Instant word, character, sentence, paragraph & reading-time count. Free, no signup.", features: ["Words, characters, sentences, paragraphs", "Reading & speaking time", "No-space character count", "Live as-you-type"], faqs: buildFaqs("the Word Counter", "words, characters, sentences, paragraphs and reading time", "as needed", "live counting as you type with zero round-trip") },
  "link-analyzer": { slug: "link-analyzer", name: "Link Analyzer", type: "Internal/External Link Audit", title: "Link Analyzer — Free Internal vs External Link Audit | SEOAcademys", description: "Audit internal vs external link distribution, nofollow ratio & anchor text. Free, no signup.", features: ["Internal vs external split", "nofollow / sponsored audit", "Anchor text table", "Per-domain counts"], faqs: buildFaqs("the Link Analyzer", "internal/external link split, nofollow ratio and anchor text", "monthly", "anchor-text distribution per outbound domain") },
  "broken-links": { slug: "broken-links", name: "Broken Link Checker", type: "Broken Link Crawler", title: "Broken Link Checker — Free Live HEAD-Check Crawler | SEOAcademys", description: "Find every broken link on a page in real time with live HEAD requests. Free, no signup.", features: ["Real HEAD requests, not regex", "Status code per link", "Internal & external coverage", "Exportable CSV"], faqs: buildFaqs("the Broken Link Checker", "every outbound link with real HEAD-request status codes", "monthly", "real network HEAD-checks instead of regex parsing") },
  "image-seo": { slug: "image-seo", name: "Image SEO Checker", type: "Image Optimization Audit", title: "Image SEO Checker — Free Alt Text, Filename & Optimization Audit | SEOAcademys", description: "Audit alt text, file names & image optimization across a page. Free, no signup.", features: ["Missing alt-text detection", "Filename quality scoring", "Dimension & format flags", "Lazy-loading audit"], faqs: buildFaqs("the Image SEO Checker", "alt text, filename quality and lazy-loading on every image", "per article", "image-by-image checklist with severity") },
  "schema-validator": { slug: "schema-validator", name: "Schema.org Validator", type: "JSON-LD Validator", title: "Schema Validator — Free JSON-LD Schema.org Validator | SEOAcademys", description: "Find every JSON-LD block, parse it & validate required properties. Free, no signup.", features: ["All JSON-LD blocks extracted", "Required-property validation", "Per-type rule set", "Inline JSON pretty-print"], faqs: buildFaqs("the Schema Validator", "every JSON-LD block and required-property check by @type", "before every publish", "per-type required-property enforcement") },
  "faq-schema": { slug: "faq-schema", name: "FAQ Schema Generator", type: "FAQ JSON-LD Builder", title: "FAQ Schema Generator — Free FAQPage JSON-LD Builder | SEOAcademys", description: "Generate FAQ schema (FAQPage JSON-LD) for Google rich results. Free, no signup.", features: ["Unlimited Q&A pairs", "FAQPage JSON-LD output", "Live preview", "Copy / download"], faqs: buildFaqs("the FAQ Schema Generator", "FAQPage JSON-LD with unlimited question/answer pairs", "per FAQ page", "live JSON-LD preview as you type") },
  "product-schema": { slug: "product-schema", name: "Product Schema Generator", type: "Product JSON-LD Builder", title: "Product Schema Generator — Free Product JSON-LD with Price & Reviews | SEOAcademys", description: "Create Product schema with price, availability & reviews. Free, no signup.", features: ["Price & currency", "Availability enum", "Reviews & aggregateRating", "Live preview"], faqs: buildFaqs("the Product Schema Generator", "Product JSON-LD with offers, availability and aggregateRating", "per product template", "complete Offer + AggregateRating output") },
  "article-schema": { slug: "article-schema", name: "Article Schema Generator", type: "Article JSON-LD Builder", title: "Article Schema Generator — Free Article / BlogPosting JSON-LD | SEOAcademys", description: "Generate Article / BlogPosting JSON-LD for any post. Free, no signup.", features: ["Article + BlogPosting types", "Headline, author, datePublished", "Image & wordCount", "Copy / download"], faqs: buildFaqs("the Article Schema Generator", "Article / BlogPosting JSON-LD with all required properties", "per article template", "complete BlogPosting field coverage") },
  "breadcrumb-schema": { slug: "breadcrumb-schema", name: "Breadcrumb Schema Generator", type: "BreadcrumbList Builder", title: "Breadcrumb Schema Generator — Free BreadcrumbList JSON-LD | SEOAcademys", description: "Create BreadcrumbList schema for site navigation. Free, no signup.", features: ["BreadcrumbList JSON-LD", "Unlimited levels", "Live preview", "Copy / download"], faqs: buildFaqs("the Breadcrumb Schema Generator", "BreadcrumbList JSON-LD for any depth of navigation", "per site template", "unlimited nesting with live preview") },
  "html-minifier": { slug: "html-minifier", name: "HTML Minifier", type: "HTML Minifier", title: "HTML Minifier — Free Live HTML Compressor | SEOAcademys", description: "Minify HTML instantly. Removes whitespace, comments & redundant attributes. Free, no signup.", features: ["Whitespace removal", "Comment stripping", "Byte-saving stats", "Copy / download"], faqs: buildFaqs("the HTML Minifier", "HTML byte size after whitespace and comment removal", "before every deploy", "byte-saving stats with one-click copy") },
  "css-minifier": { slug: "css-minifier", name: "CSS Minifier", type: "CSS Minifier", title: "CSS Minifier — Free Live CSS Compressor | SEOAcademys", description: "Minify CSS instantly. Whitespace, comments & shorthand. Free, no signup.", features: ["Whitespace removal", "Comment stripping", "Byte-saving stats", "Copy / download"], faqs: buildFaqs("the CSS Minifier", "CSS byte size after whitespace and comment removal", "before every deploy", "live byte-saving comparison") },
  "js-minifier": { slug: "js-minifier", name: "JS Minifier", type: "JavaScript Minifier", title: "JS Minifier — Free Live JavaScript Compressor | SEOAcademys", description: "Minify JavaScript instantly. Whitespace & comment removal. Free, no signup.", features: ["Whitespace removal", "Comment stripping", "Byte-saving stats", "Copy / download"], faqs: buildFaqs("the JS Minifier", "JavaScript byte size after whitespace and comment removal", "before every deploy", "live byte-saving comparison") },
  "keyword-research": { slug: "keyword-research", name: "Keyword Research", type: "Keyword Ideas Tool", title: "Keyword Research — Free Long-Tail Ideas with Volume & KD | SEOAcademys", description: "Free keyword research with long-tail ideas, intent, volume & difficulty estimates. Free, no signup.", features: ["Long-tail expansion", "Intent classification", "Heuristic volume", "Difficulty estimate", "CPC estimate", "CSV export"], faqs: buildFaqs("the Keyword Research tool", "long-tail keyword ideas with intent, volume, KD and CPC estimates", "for every new topic cluster", "intent classification per keyword") },
  "serp-preview": { slug: "serp-preview", name: "SERP Preview", type: "Google SERP Preview", title: "SERP Preview — Free Live Google Snippet Preview (Desktop & Mobile) | SEOAcademys", description: "Preview how your page appears in Google SERPs — desktop & mobile, pixel-accurate. Free, no signup.", features: ["Desktop + mobile preview", "Pixel-width truncation", "Title & description health", "Live URL slug rendering"], faqs: buildFaqs("the SERP Preview", "pixel-accurate Google desktop + mobile snippet rendering", "before every publish", "true pixel-width truncation rather than character count") },
  "meta-generator": { slug: "meta-generator", name: "Meta Tag Generator", type: "Meta Tag Builder", title: "Meta Tag Generator — Free SEO, Open Graph & Twitter Tag Builder | SEOAcademys", description: "Generate SEO, Open Graph & Twitter Card meta tags. Live HTML preview. Free, no signup.", features: ["Title, description, canonical", "Open Graph block", "Twitter Card block", "Live HTML preview", "Copy as HTML"], faqs: buildFaqs("the Meta Tag Generator", "SEO, OG and Twitter Card tags in one HTML block", "per template", "complete OG + Twitter coverage in one snippet") },
  "robots-txt": { slug: "robots-txt", name: "Robots.txt Builder", type: "Robots.txt Generator", title: "Robots.txt Builder — Free Generator with AI Crawler Rules | SEOAcademys", description: "Visually build robots.txt — including AI crawler rules (GPTBot, PerplexityBot, ClaudeBot, Google-Extended). Free.", features: ["Visual rule builder", "AI crawler presets", "Sitemap directive", "Per-bot allow/disallow", "Download as .txt"], faqs: buildFaqs("the Robots.txt Builder", "every User-agent rule including modern AI crawlers", "per site launch", "out-of-the-box AI-crawler presets") },
  "backlink-checker": { slug: "backlink-checker", name: "Backlink Checker", type: "Backlink Analyzer", title: "Backlink Checker — Free Authority & Spam Signal Analyzer | SEOAcademys", description: "Analyze backlink profile, authority score & spam signals heuristically. Free, no signup.", features: ["Authority score heuristic", "Referring domain estimate", "Spam-signal flag", "Anchor diversity"], faqs: buildFaqs("the Backlink Checker", "authority score, referring domain estimate and spam signals", "monthly", "heuristic spam-signal weighting") },
};

export function getToolMeta(slug: string): ToolMeta | undefined {
  return TOOL_META[slug];
}

export function toolJsonLd(meta: ToolMeta): object[] {
  const url = `${SITE}/tools/${meta.slug}`;
  return [
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: meta.name,
      applicationCategory: "WebApplication",
      operatingSystem: "Web Browser",
      description: meta.description,
      url,
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "2400000", bestRating: "5" },
      featureList: meta.features.join(", "),
      isPartOf: { "@type": "WebSite", name: "SEOAcademys", url: SITE },
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: SITE },
        { "@type": "ListItem", position: 2, name: "Tools", item: `${SITE}/tools` },
        { "@type": "ListItem", position: 3, name: meta.name, item: url },
      ],
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: meta.faqs.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    },
  ];
}

export const SITE_URL = SITE;
