import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Copy, Check, Download } from "lucide-react";
import { Card3D, ToolHeader } from "@/components/Card3D";
import { ToolPanel } from "./tools";

export const Route = createFileRoute("/tools/robots-txt")({
  head: () => ({
    meta: [
      { title: "Robots.txt Generator + AI Crawler Rules — SEOAcademys" },
      { name: "description", content: "Visual robots.txt builder with rules for GPTBot, GoogleExtended, PerplexityBot, ClaudeBot, and more." },
    ],
    links: [{ rel: "canonical", href: "/tools/robots-txt" }],
  }),
  component: RobotsTool,
});

const AI_BOTS = [
  { id: "GPTBot", label: "OpenAI / GPTBot" },
  { id: "ChatGPT-User", label: "ChatGPT-User (live retrievals)" },
  { id: "Google-Extended", label: "Google-Extended (Gemini training)" },
  { id: "PerplexityBot", label: "PerplexityBot" },
  { id: "ClaudeBot", label: "Anthropic / ClaudeBot" },
  { id: "CCBot", label: "Common Crawl / CCBot" },
  { id: "anthropic-ai", label: "anthropic-ai" },
  { id: "Applebot-Extended", label: "Applebot-Extended" },
  { id: "Bytespider", label: "ByteDance / Bytespider" },
];

function RobotsTool() {
  const [allowAll, setAllowAll] = useState(true);
  const [disallowed, setDisallowed] = useState("/admin\n/private\n/cart\n/checkout");
  const [sitemap, setSitemap] = useState("https://yourwebsite.com/sitemap.xml");
  const [botRules, setBotRules] = useState<Record<string, "allow" | "disallow">>(
    Object.fromEntries(AI_BOTS.map((b) => [b.id, "allow"])),
  );
  const [crawlDelay, setCrawlDelay] = useState("");
  const [copied, setCopied] = useState(false);

  const text = useMemo(() => {
    const blocks: string[] = [];
    blocks.push(`# Generated by SEOAcademys robots.txt builder`);
    blocks.push(``);
    blocks.push(`User-agent: *`);
    if (allowAll) blocks.push(`Allow: /`);
    disallowed.split("\n").map((s) => s.trim()).filter(Boolean).forEach((p) => blocks.push(`Disallow: ${p}`));
    if (crawlDelay) blocks.push(`Crawl-delay: ${crawlDelay}`);
    blocks.push(``);

    blocks.push(`# AI Crawlers`);
    AI_BOTS.forEach((b) => {
      blocks.push(`User-agent: ${b.id}`);
      blocks.push(botRules[b.id] === "allow" ? "Allow: /" : "Disallow: /");
      blocks.push(``);
    });

    if (sitemap.trim()) blocks.push(`Sitemap: ${sitemap.trim()}`);
    return blocks.join("\n");
  }, [allowAll, disallowed, sitemap, botRules, crawlDelay]);

  const copy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([text], { type: "text/plain" });
    const u = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = u; a.download = "robots.txt"; a.click();
    URL.revokeObjectURL(u);
  };

  return (
    <ToolPanel>
      <ToolHeader title="Robots.txt Builder" badge="AI CRAWLER READY" desc="Compose robots.txt visually. Control AI training bots (GPTBot, Google-Extended, Claude, Perplexity) individually." />

      <div className="grid lg:grid-cols-2 gap-6">
        <Card3D tilt={false} className="p-6 space-y-5">
          <div>
            <label className="text-sm font-medium block mb-2">Default for All Bots (User-agent: *)</label>
            <div className="flex gap-2">
              <button onClick={() => setAllowAll(true)} className={`flex-1 py-2 rounded-md text-sm border ${allowAll ? "border-success text-success bg-success/10" : "border-border text-muted-foreground"}`}>Allow All</button>
              <button onClick={() => setAllowAll(false)} className={`flex-1 py-2 rounded-md text-sm border ${!allowAll ? "border-destructive text-destructive bg-destructive/10" : "border-border text-muted-foreground"}`}>Disallow All</button>
            </div>
          </div>

          <div>
            <label className="text-sm font-medium block mb-2">Disallow Paths (one per line)</label>
            <textarea value={disallowed} onChange={(e) => setDisallowed(e.target.value)} rows={5} className="w-full px-3 py-2 rounded-md bg-background border border-border outline-none focus:border-primary font-mono text-sm" />
          </div>

          <div>
            <label className="text-sm font-medium block mb-2">Sitemap URL</label>
            <input value={sitemap} onChange={(e) => setSitemap(e.target.value)} className="w-full px-3 py-2 rounded-md bg-background border border-border outline-none focus:border-primary" />
          </div>

          <div>
            <label className="text-sm font-medium block mb-2">Crawl Delay (seconds, optional)</label>
            <input value={crawlDelay} onChange={(e) => setCrawlDelay(e.target.value.replace(/[^0-9]/g, ""))} placeholder="10" className="w-full px-3 py-2 rounded-md bg-background border border-border outline-none focus:border-primary" />
          </div>

          <div>
            <label className="text-sm font-medium block mb-3">AI Crawler Rules</label>
            <div className="space-y-1.5">
              {AI_BOTS.map((b) => (
                <div key={b.id} className="flex items-center justify-between gap-3 rounded-md border border-border bg-background px-3 py-2">
                  <div className="text-sm min-w-0">
                    <div className="font-mono text-xs">{b.id}</div>
                    <div className="text-[11px] text-muted-foreground truncate">{b.label}</div>
                  </div>
                  <div className="flex gap-1 shrink-0">
                    <button onClick={() => setBotRules({ ...botRules, [b.id]: "allow" })} className={`text-[11px] px-2 py-1 rounded ${botRules[b.id] === "allow" ? "bg-success text-white" : "bg-secondary text-muted-foreground"}`}>Allow</button>
                    <button onClick={() => setBotRules({ ...botRules, [b.id]: "disallow" })} className={`text-[11px] px-2 py-1 rounded ${botRules[b.id] === "disallow" ? "bg-destructive text-white" : "bg-secondary text-muted-foreground"}`}>Block</button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </Card3D>

        <div className="rounded-xl border border-border bg-[#0b1020] text-emerald-200 overflow-hidden shadow-[var(--shadow-3d)] h-fit sticky top-32">
          <div className="flex items-center justify-between px-4 py-2 border-b border-white/10 text-xs text-white/70">
            <span className="font-mono">robots.txt</span>
            <div className="flex gap-2">
              <button onClick={copy} className="inline-flex items-center gap-1.5 hover:text-white">{copied ? <Check className="size-3" /> : <Copy className="size-3" />} {copied ? "Copied" : "Copy"}</button>
              <button onClick={download} className="inline-flex items-center gap-1.5 hover:text-white"><Download className="size-3" /> Download</button>
            </div>
          </div>
          <pre className="p-4 text-xs font-mono leading-relaxed overflow-auto max-h-[640px] whitespace-pre-wrap">{text}</pre>
        </div>
      </div>
    </ToolPanel>
  );
}
